# Generated by Django 4.1.5 on 2023-01-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Picture',
        ),
    ]
