# Generated by Django 4.1.5 on 2023-01-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_rename_image_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='img',
            new_name='image',
        ),
    ]
